apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "whoami-backend.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.labels.app | default "whoami" }}
    side: {{ .Values.labels.side | default "backend" }}
    managed-by: {{ .Values.labels.managedBy | default "Helm" }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | default "cilium-gateway" }}
      namespace: {{ .Values.gateway.namespace | default "network" }}
  hostnames:
    - {{ .Values.route.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.route.path | default "/" | quote }}
          timeouts: {{ .Values.route.timeout | default "3600s" | quote }}
      backendRefs:
        - name: {{ include "whoami-backend.fullname" . }}
          namespace: {{ .Values.namespace | default "default" }}
          port: {{ .Values.service.port | default 8080 }}
